# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20170706_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
